window.alert("Hello baby!")
window.alert("Are you still mad at me?")
window.alert("I'm sorry about what happened last night...")
window.alert("Sorry if I make you angry and upset:<")
window.alert("You're not the problem baby, It's me who always think that I'm not a good girlfriend for you...")
window.alert("I'm sorry for all the things that I've done to you. I'm trying to be the best for you.")
window.alert("Iloveyou and I don't want to lose you...")
window.alert("You're only the reason why I take a good care of myself so that I won't get sick and be able to take care of you if I had some time...")
window.alert("I'm sorry if I'm always so selfish to the point that you won't open up on me because you're always scared that it could all end up to arguements...")
window.alert("If I'm the reason of our arguments I can't stop thinking that I'm not a good gf for you...")
window.alert("That you can find someone else to understand you and be there for you")
window.alert("and you can open up to her without being scared...")
window.alert("I'm sorry if I always think that I'm not good enough for you that you deserve much better...")
window.alert("but at the same time...")
window.alert("I can't lose you...")
window.alert("If I lose you, I'll cry myself to d*e.")
window.alert("I'm sorry now my love...")
window.alert("All that I can think is to be a better gf for you... To be your safe place...")
window.alert("Iloveyou and I'm sorry...")
window.alert("Please don't be angry na... ")
window.alert("Imissyou na po:<")